// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trprouvrswkkqctpwouk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRycHJvdXZyc3dra3FjdHB3b3VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MjY5NjAsImV4cCI6MjA2NjUwMjk2MH0.Dqv7_RI-trBrQqd1X2UMgmtpZiOHM9wjy7zK8kqmrJA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);